### ISSUE TITLE
Structure the front page of the documentation

### ISSUE THREAD

**Issue by parisk** [sourcelair/docs.stolos.io#16]
We have to structure the front page of the documentation, in order to help our users find what they want in the easiest way possible. The things that we have to take into account are:
- [x] decide which information should be displayed in the front page
- [x] make sure that all content is accessible from the front page
## To-do
- [ ] Create a separate page for each collection and list in each page the relative articles
- [ ] Keep the front page only for:
  - Brief intro
  - Listing collections with brief intro
  - Cherry picked articles
